/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guanaida_myopencv_NativeGrabCut */

#ifndef _Included_com_guanaida_myopencv_NativeGrabCut
#define _Included_com_guanaida_myopencv_NativeGrabCut
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guanaida_myopencv_NativeGrabCut
 * Method:    grabCutFromJNI
 * Signature: (JIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_guanaida_myopencv_NativeGrabCut_grabCutFromJNI
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
