/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guanaida_myopencv_NativeGrabCut */

#ifndef _Included_com_guanaida_myopencv_NativeGrabCut
#define _Included_com_guanaida_myopencv_NativeGrabCut
#ifdef __cplusplus
#include <string>
#include "opencv2/imgcodecs.hpp"
#include "opencv2/highgui.hpp"
#include "opencv2/imgproc.hpp"
#include <iostream>

using namespace std;
using namespace cv;

extern "C" {
#endif
/*
 * Class:     com_guanaida_myopencv_NativeGrabCut
 * Method:    grabCutFromJNI
 * Signature: (JIIII)J
 */
JNIEXPORT Mat* JNICALL Java_com_guanaida_myopencv_NativeGrabCut_grabCutFromJNI
  (JNIEnv *env, jobject instance, jlong m,jint l, jint t, jint r, jint b) {

    // TODO
    Mat *img = (Mat *) m ;

    Rect rect(l,t,r - l,b - t);

    Mat firstMask;
    Mat bgModel;
    Mat fgModel;

    grabCut(*img,
            firstMask,
            rect,
            bgModel,fgModel,
            5,
            GC_INIT_WITH_RECT);
    compare(firstMask,GC_PR_FGD,firstMask,CMP_EQ);

    Mat *foreground = new Mat(img->size(),CV_8UC3,Scalar(255,255,255));

    img->copyTo(*foreground,firstMask);

    return foreground;

}

#ifdef __cplusplus
}
#endif
#endif
