/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guanaida_myopencv_NativeGrabCut */

#ifndef _Included_com_guanaida_myopencv_NativeGrabCut
#define _Included_com_guanaida_myopencv_NativeGrabCut
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guanaida_myopencv_NativeGrabCut
 * Method:    grabCutFromJNI
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_guanaida_myopencv_NativeGrabCut_grabCutFromJNI
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
