/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guanaida_myopencv_NativeGrabCut */

#ifndef _Included_com_guanaida_myopencv_NativeGrabCut
#define _Included_com_guanaida_myopencv_NativeGrabCut
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guanaida_myopencv_NativeGrabCut
 * Method:    grabCut
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_guanaida_myopencv_NativeGrabCut_grabCut
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
